### PR TITLE
Goat a11y october

### PR DESCRIPTION
**Pull request by philcon93**
- Need to update styles from app.css and custom.js into themes that depend on skeletal templates.

### CODE REVIEW

**Comment by philcon93** [comment]
#55

**Comment by brandonsheppard** [comment]
Closing PR, apparently not ready?

**Comment by philcon93** [comment]
Alright all Neto themes have been updated and are ready for the Goat a11y express.

**Comment by philcon93** [comment]
This should also address #292

**Comment by robm2002** [comment]
Reviewed with Phil, all looking bloody lovely.

**Comment by philcon93** [comment]
You closed this? I think you asked for changes instead of approved in your review

**Pull request merged**
