### PR TITLE
Updated inputs to type email

### PR DESCRIPTION
**Pull request by jakesergeant**
Updated the login/register email input to be `type="email"`.

### CODE REVIEW

**Comment by matt-downs** [comment]
This may not work well for wholesale customers to use a username to log in (if anyone even does that?)

**Comment by jakesergeant** [comment]
if we're accepting usernames in this field then the label should be updated to reflect that to avoid confusion

**Comment by matt-downs** [comment]
But that will confuse regular customers because they never got to choose a username 😪

I think the solution would be to either: 
- Hide the username field for wholesale customers too
- Show the username field on the regular signup form in addition to the wholesale registration

**Comment by philcon93** [comment]
@jakesergeant what is your plan here? I'm okay to close this as it's not a point of concern that we do not specify the username. We are not removing functionality by only allowing users to place in an email here and we do not want to make it so users have to place in a username on registering. 

I would be okay to change the labels to just be 'Username' and 'Password' on the login form, as the placeholder text for username/email is an email, which I believe gives enough context to the user they can place in their email. But if this isn't a point of concern that is being brought up in support, or isn't an item that design changes for tweaks/projects, then change is unnecessary.

**Pull request closed without merging**
