### PR TITLE
Pre order stock investigation

### PR DESCRIPTION
**Pull request by brandonsheppard**
# Background

There are two reasonable ways that merchants want to handle stock for pre-orders:

1. Stock is tracked for all pre-orders. The merchant literally orders in their pre-order products and hosts them in a warehouse. This stock is held behind an embargo which allows the merchant to sell the stock, but not dispatch until a specific date. This date is the `arrival_date` in Neto.
2. Stock is not tracked for pre-order products because they are not yet in a warehouse. Merchants have not yet received the goods, but may have some incoming or have pre-arranged a quota of pre-orderable stock.

In the past, Neto's front-end templates have only supported scenario 1, but our software validation supports scenario 2 fine. This PR (up for review and discussion) adjusts our buying logic to instead support scenario 2. Based on customer feedback over the years, I believe that scenario 2 is now more common and desirable.

# Summary

In this PR, I have adjusted various blocks of logic to use `available_preorder_quantity` instead of `store_quantity` in preorder stock/availability checks. This better reflects the logic our software uses for validation of the **pre-order quantity** stock field, which it treats as a quota independent of the actual stock levels of an item.

# Impact of this change

- Products which are not in stock, but **have a pre-order quantity** and **have an arrival date set in the future**, will be purchasable as a pre-order from the webstore. The available quantity of this product will not be taken into account at all.
- Purchasing a product which is on preorder will correctly diminish the `available_preorder_quantity` and therefore eventually disable pre-orders. 

This needs to be discussed (is this change actually desirable) and significantly tested (there are many scenarios I have not manually tested here, including what happens when stock is updated.

Note that the tag I have used, `available_preorder_quantity`, was not made for this purpose. It simply happens to exist and fulfil this need. This obviously increases the need for thorough testing.

### CODE REVIEW

**Comment by philcon93** [comment]
Quick testing data 

- available_preorder_quantity - [@available_preorder_quantity@] 
- store_quantity - [@store_quantity@]
- preorder - [@preorder@] 

---

# No stock with stock coming

screen shot 2018-01-04 at 2 52 09 pm
screen shot 2018-01-04 at 2 52 23 pm

---

# In stock with no incoming stock

screen shot 2018-01-04 at 2 54 40 pm
screen shot 2018-01-04 at 2 54 26 pm

---

# In stock with stock coming

screen shot 2018-01-04 at 2 55 19 pm
screen shot 2018-01-04 at 2 55 12 pm

**Comment by matt-downs** [comment]
+1 for this PR

**Comment by brandonsheppard** [comment]
I think we should roll this into the BS4 upgrade so it's very obvious which sites use old logic VS new logic. Sound good? 

cc: @philcon93  @matt-downs  @craigblunden

**Comment by matt-downs** [comment]
@brandonsheppard Sounds good! 🎉

**Comment by philcon93** [comment]
@brandonsheppard can you change the branch this PR is merging into, to 'feature/b4'

**Comment by brandonsheppard** [comment]
Done @philcon93 

Will need some work, though 😊

**Comment by philcon93** [comment]
Tested on different product types and it works correctly. This PR fixed up child product buying logic and kit buying logic as well (bad and/or logic!).

There is one particular issue though; 

A product has 1 available qty, would be preorder:

screen shot 2018-05-01 at 10 36 12 am

If you add 2 of this product to cart it will error on the shopping cart because there isn't that amount of stock, this is good, we want this. This issue though is the error wording, 'We have 0 in stock';

screen shot 2018-05-01 at 10 39 17 am

The wording is correctly because there is no stock, but there is 1 available qty, and if the user changed their amount to 1 then everything is okay;

screen shot 2018-05-01 at 10 39 33 am

Maybe we need to change this error message?

**Comment by matt-downs** [comment]
Error message is ID `319`:

`Sorry. We don't have enough '[@name@] ([@SKU@])' in stock to fulfill your order[%thumb_list type:'products' filter_sku:'[@SKU@]'%][%PARAM header%]: we have&nbsp;[%END PARAM%][%PARAM *body%][@stock@][%END PARAM%][%PARAM footer%]&nbsp;in stock[%END PARAM%][%end thumb_list%]. Please change the qty on order in your shopping cart and click update. Then try to checkout again.`

**Comment by matt-downs** [comment]
I just realised that if a customer has the "Only show in stock product in thumb list" setting enabled then items put on preorder using this logic will not show on the website, as they have a Qty On Hand < 0

I still think that we should go ahead with this PR, but this should be added as a gotcha in our documentation. 

Maybe the logic behind the `[@CONFIG:IGNORE_NOSTOCK_THUMB@]` config could be changed in the future to take the preorder qty into account? 

@philcon93 thoughts?

**Pull request merged**
