### PR TITLE
Topic/nov 2019

### PR DESCRIPTION
**Pull request by philcon93**
Updating v3 Skeletal branch to include the following features:

- Updated payment icon function to include web payment icons (footer and invoice),
- Different shipping calculator set up for product and cart pages,
- New pre-order logic.

Also updated npm dependencies to make it easier to develop between this branch and latest Skeletal, and to remove security issues:

- gulp - 4.0.2
- bootstrap - 3.4.1

---

Requires complete end to end testing for all features, the majority of premium themes are still Bootstrap 3 and will be depending off this branch for their November 2019 update.

### CODE REVIEW

**Comment by shorsup** [comment]
I think I've come across another issue with the new pre-order functionality.
For editable kits, the new pre-order functionality doesn't allow you to add a quantity of that product to the kit (it's disabled).

Example: http://premiumthemes.neto.com.au/kit?preview=y

**Comment by philcon93** [comment]
@shorsup updated breadcrumb structured data. Those other issues are not issues with this branch/template but Neto. So it will also be an issue on the branch going into master - `pre-order-stock-investigation`.

- The sidebar filter one will be with the logic in the product_filer base function.
-  The kit one is because that product has the data tag `fixed_assemble` set to true, which is set in the item_kitting base function.

The kit one might be able to have a workaround via template but unsure/untested, but the filter one will require updates to the base function.

**Comment by philcon93** [comment]
@shorsup can we check if the following changes are a solution for pre-order kit items [4be71e4](https://github.com/NetoECommerce/Skeletal/pull/506/commits/4be71e4039225d08891f5d49ec720326c60f7a71).

If this works we will need to add it to https://github.com/NetoECommerce/Skeletal/pull/419

**Comment by shorsup** [comment]
@philcon93 Yes, this fix works correctly.

**Pull request merged**
