### PR TITLE
B4

### PR DESCRIPTION
**Pull request by philcon93**
Updated CSS framework from Bootstrap 3.3.6 to 4.1.

Almost ever file in the Skeletal repo has been updated in some way to accommodate for this update. There are a huge amount of benefits on updating our CSS framework; better modern browser support, using modern CSS e.g Flexbox, simplified components while extensive utility classes, its just a great move forward. Bootstrap has created a migration article which talks about what is new:

- https://getbootstrap.com/docs/4.0/migration/#summary 

Our gulp build process has been updated to use SASS and also use the JS from the theme dependency. ie Bootstrap and Popper.js are included via package.json and the gulp task `gulp js` will bring those relevant JS files into the theme. This is much better as it couples the theme directly with its dependency and when Bootstrap gets updated for new features or bug fixes we can test the update and update our dependencies.

All b@se has also been updated to use modern syntax, e.g removal of comment tags around b@se functions and use of data/config tags instead of data/config functions.

Need to discuss how this can be potentially rolled out, as all themes depend off Skeletal, themes would need to be updated to Bootstrap4 if this was merged into master. Or this branch becomes its own repo/fixed branch and new features are continued on it, while bug fixes are done on both? Would then need to discuss how theme developers could choose which theme they wish to use as their 'master' theme. Having the option to develop a theme on B3 or B4 gives more creative freedom to the developer, hopefully meaning great themes/designs being developed.

Demo site;

- http://devphil.neto.com.au/?nview=skeletal-b4

Time to learn up kid;

- https://getbootstrap.com/docs/4.1/getting-started/introduction/

### CODE REVIEW

**Comment by craigblunden** [comment]
I think we've discussed this before but I think we should have a Skeletal 2.0 (or whatever the best naming convention is) theme. 

Keep BS3 on its own repo and progressively enhance BS4 with its own build pipeline so it doesn't affect other branches but can still be utilised by customers, partners and internally. 

This also gives us an opportunity to upgrade Font Awesome without affecting other themes.

**Comment by philcon93** [comment]
It should still be this repo as its the same theme, but make it a protected branch. This would also help to keep this branch up to date, as you could cherry pick and/or merge from master whenever there is a change. The theme-starter-kit would just need to be updated so you can target branch/release when the theme generates/compiles.

**Comment by robm2002** [comment]
Hey mate,

A few issues (understandably):

- Upsell page isn't showing any products.
- There's quite a few different gray colours used for borders - e.g. input fields, btn-default in add to cart modal, and "Sort" field on category page.
- Header styling broken on "approve_quote" page.

[Issues.zip](https://github.com/NetoECommerce/Skeletal/files/1926554/Issues.zip)

**Comment by matt-downs** [comment]
Fantastic work! 

Here are a few screenshots of the things that I think should be changed. This ended up being more of a skeletal teardown haha

[b4-review.zip](https://github.com/NetoECommerce/Skeletal/files/1928036/b4-review.zip)

🐐

**Comment by brandonsheppard** [comment]
This is great—needs a little tweaking here and there but pretty damn solid start.

I think we should try to overhaul the navbar a bit. The standard Bootstrap hamburger menu is pretty crap.

**Comment by philcon93** [comment]
*Note:* Bootstrap stateful button function is no longer default functionality;

- https://getbootstrap.com/docs/3.3/javascript/#buttons-stateful

Commit #dd90821 solves this while also fixing #383. Something we seemed to have missed with that PR; `product_variationInit` onReady will have reloaded the templates, so we dont have to try to reset the state of the button, it has already been reset to reflect the new product variations content.

We have to do a click event both on document ready and in the onReady state, as document ready occurs at the start, while onReady only occurs after `product_variationInit` has finished.

**Comment by philcon93** [comment]
dd90821 didn't ensure the addtocart button wasn't clickable while loading. For some trying to fix this   didn't play well with neto.js and adding an attribute of disabled would break the addtocart functionality. 2 hours later and reading too much about event delegation, I finally fixed this up by ensuring this event doesn't bubble up and not targeting the addtocart button directly. 

Also as a plus, this fixed something #383 didn't find either; using the shipping calculator reloads the templates, breaking the addtocart loading state. The event listener in #383 would only fix it when a variation is selected. Because of this, the event listener can't target the addtocart directly but with a parent element with an `on` event.

**Comment by philcon93** [comment]
Here is an example gist of how extremely useful SASS mapping is, which was added in 00608cd:

- https://gist.github.com/philcon93/5553550f69fe236b112ff602a3312b74

**Comment by robm2002** [comment]
^ 
[issues.zip](https://github.com/NetoECommerce/Skeletal/files/1965512/issues.zip)

**Comment by robm2002** [comment]
Some elements are using the original 'fa' classes on these commits:
- https://github.com/NetoECommerce/Skeletal/pull/386/commits/09ea3233a5275dc0cbca84e17438047cc30a456e
- https://github.com/NetoECommerce/Skeletal/pull/386/commits/d7cc46f4838323e49abec213e4416e999503e509

Apart from that, everything looks good!

**Comment by matt-downs** [comment]
## Weird vertical offset on third level sidebar dropdowns 
image

**Comment by philcon93** [comment]
Solves #386

**Pull request merged**
