### PR TITLE
Display parent review stars product page

### PR DESCRIPTION
**Pull request by mmwoods**
Solves #313 and #314

Removes data tag, and pulls reviews data from parent product, for use within the product stars, below the product title.

### CODE REVIEW

**Comment by mmwoods** [comment]
@philcon93 It should display the review stars on page load and when selecting a variation. It appears that due to the product SKU being updated to being the child product's SKU when selecting a variation, the above code no longer works, as there is no longer a valid [@^reviews@].

This is mentioned in case #303 as being a problem that can be solved by moving the reviews code to the product template file and not the header, and using the previous code in skeletal not the commit above. #314

**Comment by philcon93** [comment]
@mmwoods would you like to refactor your code in this PR to fix those two skeletal issues or should this PR be closed?

I don't believe a solution would be to place the reviews outside the header template as it would require significant template changes to preserve the existing layout.

As a possible solution, you could check if current SKU has reviews, if not check if it has a parent SKU, if it does check if it has reviews. It would be extensive logic that might be costly but it would give the desired results.

**Comment by matt-downs** [comment]
@philcon93 would something like this work? It will pull the reviews from the parent product (if available). 
```html
[%if [@parent_sku@]%]
	[%product sku:'[@parent_sku@]'%]
		[%param *body%]
			[%set [@^reviews@] %][@reviews@][%/set%]
			[%set [@^rating@] %][@rating@][%/set%]
		[%/param%]
	[%/product%]
[%/if%]

[%if [@reviews@] > 0%]
	<span class="small" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
		[%set [@ratings-count@] = 1 /%]
		[%while [@ratings-count@] <= [@rating@]%]
			[%set [@ratings-count@] = [@ratings-count@]+1 /%]
			<i class="fa fa-star"></i>
		[%/ while%]
		[%while [@ratings-count@] <= 5%]
			[%set [@ratings-count@] = [@ratings-count@]+1 /%]
			<i class="fa fa-star-o"></i>
		[%/while%]
		Rated <span itemprop="ratingValue">[@rating@]</span>/<span itemprop="bestRating">5</span> based on <span itemprop="ratingCount">[@reviews@]</span> review/s.
	</span>
[%/if%]
```

**Comment by philcon93** [comment]
Test that code out to see if it works! You might have to use a custom data tag instead of trying to override the parents `reviews ` `rating`.

I would probably think the following way would be easier to understand; it checks if there are any reviews, then check if there is a parent.

[%if [@reviews@] > 0%]
	...
[%else%]
	[%if [@parent_sku@]%]
		[%product sku:'[@parent_sku@]'%]
                 	[%if [@reviews@] > 0%]
        		...
			[%/if%]
		[%/product%]
	[%/if%]
[%/if%]

**Comment by matt-downs** [comment]
Shouldn't we just always show reviews from the parent product? This means that the star rating in the header will always be the same as what is displayed in the reviews section further down the page.

The `SHOW_CHILD_PRODUCT_REVIEWS` config is also enabled by default which means child reviews will be reflected in the parent rating anyway.

**Comment by philcon93** [comment]
@mmwoods  and @matt-downs will you guys be updating this PR to this new code or should we close this and move the discussion to its original issue?

**Comment by matt-downs** [comment]
@philcon93 I'd be happy to update but I don't currently have permissions to push to this branch... 😬

**Comment by philcon93** [comment]
^ @brandonsheppard can we get matt-downs into the neto design github club?

**Comment by matt-downs** [comment]
@philcon93 Sure do! I will assign this to myself

**Comment by matt-downs** [comment]
I am using the `load_ajax_template` to control the scope of the reviews like so:
- On a product with variations/children:
    - If `SHOW_CHILD_PRODUCT_REVIEWS` is enabled, the reviews from the parent product will always be shown (this will show all reviews made on child products too).
    - if `SHOW_CHILD_PRODUCT_REVIEWS` is disabled, the reviews from the currently selected child will be shown and updated each time a variation is switched.
- On a regular product reviews will be shown as normal. 

The `load_ajax_template` has `preload` enabled so effectively it will act as a `load_template` function with a variable scope.

Looking at the response times for the `/ajax/ajax_template` request to render the updated header template shows no noticeable performance implications. 

@philcon93 whadoyathink? 😋

**Comment by philcon93** [comment]
This seems to be working well but I just want to confirm the use of `config:show_child_product_reviews`.

---

This product has one review on its parent:

- http://devphil.neto.com.au/kartell-masters-by-philippe-starck-coneugeni-quitl

If `config:show_child_product_reviews` is set to false then the logic:

- `[%if [@parent_sku@] and [@config:show_child_product_reviews@]%]` 

would be false and it would use the child sku, equalling to not showing the review stars in the header. But I assume we would want to show the stars, as it displays in the tab section below so shouldn't the logic just be simply:

- `[%if [@parent_sku@] %]`

The header section should reflect the tab section lower on the page, and the tab section only cares about the parent product / standard product, so adding this config in the logic is unnecessary complexity and I'm pretty sure this config isn't accessible unless using the advance config page, so the majority of merchants wouldn't change this.

**Comment by mmwoods** [comment]
@philcon93 I agree, the two options are to either remove the config from the header, or to add extra logic to the tabs.

In my opinion more customers want to show reviews rather than hide them, so removing the config would make the most sense to me.

**Pull request merged**
