### PR TITLE
Preorder logic

### PR DESCRIPTION
**Pull request by philcon93**
Original PR #316 

After planning on updating all other child themes so they would have the same preorder logic as #386 when it got merged in, we thought it would be better to wait and do the preorder logic change as a seperate PR all at once and with possibly to customise it.

### CODE REVIEW

**Comment by lanechr** [comment]
I belive this logic would mean if a user has stock in a warehouse and wants to make incoming stock available for preorder (to ensure people can still buy if the available stock runs out) the customer would be forced to preorder instead of just adding to cart, even though there is stock available?

Would it be better to also check that they are out of available stock as well with:
`[%IF [@store_quantity@] < 1 AND [@preorder@] AND [@available_preorder_quantity@] > 0 %]`

**Comment by Naraceaus** [comment]
@lanechr the issue here is that what happens when there are 2 in stock, 4 on preorder and a customer orders three. At least if the preorder is default the customer will not be disillusioned into thinking the item will come faster. If we do choose the logic you mentioned we would need to update the template files to also show the number available and the number for preorder. Since many users don't want to display stock levels this isn't ideal.

**Comment by philcon93** [comment]
New logic in templates follows this pattern:

```
[%if [@available_preorder_quantity@] > 0 AND [@preorder@] AND [@config:WEBSTORE_USE_PREORDER_QUANTITY@]%]
...
[%elseif [@store_quantity@] > 0 AND [@preorder@] AND ![@config:WEBSTORE_USE_PREORDER_QUANTITY@]%]
...
[%elseif [@store_quantity@] > 0 AND ![@preorder@] %]
...
[%elseif [@store_quantity@] < 1 AND [@config:ALLOW_NOSTOCK_CHECKOUT@] %]
...
[%else%]
...
[%/if%]
```

Product stock:

setup

With config set to true:

page_02

With config set to false:

page_01

**Comment by philcon93** [comment]
Organising all themes to have new logic before merging PR.

**Comment by shorsup** [comment]
**Editable kit issue**
The new pre-order functionality doesn't allow you to add a quantity to that product (it's disabled).

This is because the product has the data tag fixed_assemble set to true, which is set in the item_kitting base function.

Example: http://premiumthemes.neto.com.au/kit?preview=y&nview=amplify

**Pull request merged**
