### PR TITLE
Replaced [@thumb@] with asset_url function

### PR DESCRIPTION
**Pull request by craigblunden**

### CODE REVIEW

**Comment by matt-downs** [comment]
@craigblunden is this the only area where this needs to be changed?

**Comment by philcon93** [comment]
@matt-downs  nope there is 11 instances of the thumb data tag in Skeletal, a lot of those are for the add to cart functionality. 
@craigblunden can you go into why this is needed? @quatlin has said the thumb data tag issue will be fixed so this tag can still be used correctly?

**Comment by craigblunden** [comment]
Honestly, I just fixed it for a client and Elliot said we should probably change it on skeletal so I just did it. 

I suppose consistency should be taken into account, why use different tags in different places? Is one more performant than the other?

**Comment by philcon93** [comment]
For constancy you will want to get the other spots this data tag is used is Skeletal. I would stay away from the hidden inputs that use the thumb data tag as the default image should be the one generated from the system instead of a user defined one from `[%param default%]` in `[%asset_url%]`. Templates that use this data tag for an image are; shopping_cart and upsell, products template, child_products.

Definitely look into if either one is more performant than the other @craigblunden.

**Comment by craigblunden** [comment]
awwww, ye?

**Pull request closed without merging**
