### PR TITLE
Hide product page shipping calculator for service items

### PR DESCRIPTION
**Pull request by matt-downs**
See issue #335

### CODE REVIEW

**Comment by philcon93** [comment]
Have you tested this @matt-downs? I'm pretty sure service_only doesn't work well.

**Comment by matt-downs** [comment]
@philcon93 Yes it looked like it was working correctly when I tested it. 

What kind of circumstances would this behave weirdly? I can double check its working as intended

**Comment by philcon93** [comment]
@matt-downs when service_only isn't set so its undefined not 'n'. 
Setting a service item on parent vs setting it on variations, does it inherit correctly?

**Comment by matt-downs** [comment]
@philcon93 so I have just tested this further:
### Regular product 
Works as intended
### Product with variations:
It will in inherit the value from each child that is selected, as the AJAX is reloaded.
### Product with children:
The `buying_options` template won't be displayed, instead the `child_products` template is loaded without a shipping calc.

**Pull request merged**
