### PR TITLE
Display Out of Stock for relevant SKUs by default

### PR DESCRIPTION
**Pull request by craigblunden**

### CODE REVIEW

**Comment by bloycey** [comment]
I've made a similar pull request here #294 . This pull requests includes the code in all sections of the list variations function (e.g. radio buttons, images, etc) whereever the product name appears.

The other difference is the base tag being used. This pull request uses [@variation_store_qty@] whereas mine uses [@variation_qty@]. I only found [@variation_qty@] to work on a live site.

**Comment by philcon93** [comment]
@craigblunden can you see if `[@variation_store_qty@] ` should be used or `[@variation_qty@]`?
We can then merge #294 and #293 together

**Comment by matt-downs** [comment]
Bump

**Comment by philcon93** [comment]
Been testing this and im pretty keen to approve, but the data tags are confusing.

I have this logic for testing in the specific option:
`[@value_name@] - [@variation_store_qty@]/[@variation_qty@] - [%if [@variation_store_quantity@] < 1 %] (Out of Stock) [%/if%]`

And this is how it outputs:
screen shot 2018-02-21 at 10 56 54 am

So should it be `variation_store_qty` or `variation_qty`? `variation_store_qty` works but `variation_qty` actually give a value???

**Comment by craigblunden** [comment]
I think we should use `variation_qty` if it produces an actual value. It'll reduce confusion in the long run. I swear I tested it on Andrew's version and it didn't work but my comment doesn't really give any context to work with. Lesson learned.

**Comment by philcon93** [comment]
Yeah thats good @craigblunden can you change this PR to use the `variation_qty ` data tag instead and fix up the conflict?

**Pull request merged**
