### PR TITLE
Product page accordion tabs

### PR DESCRIPTION
**Pull request by jakesergeant**
Our default product page tabs will visually break on smaller devices. This PR will convert the tabs to an accordion using only CSS. 

I've set up an example here: http://jake-sergeant.neto.com.au/intel-core-i5-4460-quad-core-lga-1150-3.2ghz-cpu-p?nview=skeletal-tabs

### CODE REVIEW

**Comment by matt-downs** [comment]
Pretty cool!

Is there any way this could be done without duplicating all of the code though? I can't see this being very fun to support. 😢 

Eg: customer wants to add a content zone to the bottom of their description - they now have to add it in two locations.

**Comment by jakesergeant** [comment]
@matt-downs The only part that is duplicated is the title, the content of the tab is entered once. Unfortunately with the title, that looks the best way to do it.

**Comment by matt-downs** [comment]
Oh sweet! Github diffs are hard to read sometimes 😂 

@jakesergeant The only other suggestion I have is to have the description accordion open by default.

**Comment by philcon93** [comment]
Yo @jakesergeant you got conflicts with this PR, also can you ensure all styles in style.css are theme editor styles, all other styles should be in app.css, this particularly would be in the _neto.less partial.

**Comment by philcon93** [comment]
@jakesergeant lets us know if your keen to keep going with this PR or i'll close it :)

**Comment by jakesergeant** [comment]
@philcon93 updated!

**Pull request merged**
